/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations, useVideoTexture } from '@react-three/drei';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { Matrix3 } from 'three';

const DemoComputer = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/computer.glb');
  const { actions } = useAnimations(animations, group);

  const txt = useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4');


   // Créez une transformation matricielle pour inverser horizontalement
   /**Cette approche utilise useMemo pour créer la matrice de transformation une seule 
    * fois et l'applique à la texture dans le hook useEffect. La clé est de définir matrixAutoUpdate 
    * = false pour empêcher Three.js de réinitialiser automatiquement la matrice. */

  // Create UV transformation matrix to scale and position the video correctly
  const uvTransform = useMemo(() => {
    const matrix = new Matrix3();
    // Adjust these values to fit your screen
    const scaleX = 2.5;  // Decrease to make video narrower
    const scaleY = 2.5;  // Decrease to make video shorter
    const offsetX = 1; // Adjust horizontal position
    const offsetY = 1; // Adjust vertical position
    
    matrix.set(
      scaleX, 0, offsetX,
      0, scaleY, offsetY,
      0, 0, 1
    );
    return matrix;
  }, []);

  useEffect(() => {
    if (txt) {
      txt.flipY = false;
      // Apply the transformation UV
      txt.matrix = uvTransform;
      txt.matrixAutoUpdate = false;
      
      // Set wrapping and repetition
      txt.wrapS = txt.wrapT = 1000; // ClampToEdgeWrapping
      txt.repeat.set(1, 1);
    }
  }, [txt, uvTransform]);

  

   useGSAP(() => {
    gsap.from(group.current.rotation, {
        y:Math.PI/2,
      duration: 4,
      scale:.2,
      ease: 'power3.out',
    });
  }, [txt]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, .6, -0.049]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.0018}>
          <group name="Scene" position={[1314.269, -129.439, -1091.809]}>
            <mesh
              name="monitor-screen"
              castShadow
              receiveShadow
              geometry={nodes.PIED_ALIM_Mat13_0.geometry}
              material={materials['Mat.13']}
              position={[2.922, -64.916, 58.43]}
            >
                
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Extrusion_Extrusion_1_Mat14_0.geometry}
              material={materials['Mat.14']}
              position={[2.391, 86.136, 61.163]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Extrusion_Extrusion_Mat1_0.geometry}
              material={materials['Mat.1']}
              position={[2.391, 189.283, 53.848]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.TROU_CABLE_Mat2_0.geometry}
              material={materials['Mat.2']}
              position={[1.894, -40.708, -136.665]}
            />
          </group>
          <group position={[183.252, 112.138, -1415.142]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.ECRAN_Mat24_0.geometry}
              material={materials['Mat.24']}
              position={[-362.774, 397.193, 163.866]}
            >
                <meshBasicMaterial map={txt} toneMapped={false}
      />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.VIS_REGLAGE1_Mat26_0.geometry}
              material={materials['Mat.26']}
              position={[-87.198, -194.803, -771.841]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SOCLE_Mat14_0.geometry}
              material={materials['Mat.14_0']}
              position={[-185.191, -228.038, -673.286]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.SOCLE2_Mat12_0.geometry}
              material={materials['Mat.12']}
              position={[-185.191, -255.048, -230.641]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.VIS_REGLAGE2_Mat26_0.geometry}
              material={materials['Mat.26']}
              position={[-247.44, -229.14, -772.271]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.TROU_CABLE_2_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[-363.138, -210.886, -763.441]}
              rotation={[-0.1, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.PLAQUE_AL_Mat14_0.geometry}
              material={materials['Mat.14_0']}
              position={[-363.138, -202.081, -763.441]}
              rotation={[-0.1, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CRT_CAISSON_2_Mat14_0.geometry}
              material={materials['Mat.14_0']}
              position={[-181.221, 324.722, -707.584]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.VIS_ECROU_Mat23_0.geometry}
              material={materials['Mat.23']}
              position={[-456.794, -245.608, -765.395]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CB_Mat14_0.geometry}
              material={materials['Mat.14_0']}
              position={[-183.252, -246.254, -783.025]}
              rotation={[Math.PI, 0, Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.NOT1_Mat21_0.geometry}
              material={materials['Mat.21']}
              position={[-167.193, 206.009, -1146.225]}
              rotation={[Math.PI, 0, Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.NOT2_Mat20_0.geometry}
              material={materials['Mat.20']}
              position={[-121.473, 7.786, -1144.887]}
              rotation={[Math.PI, 0, Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.V_Mat23_0.geometry}
              material={materials['Mat.23_0']}
              position={[483.826, -132.943, 248.223]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.B_Mat23_0.geometry}
              material={materials['Mat.23_0']}
              position={[380.985, -132.943, 248.223]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.G_Mat23_0.geometry}
              material={materials['Mat.23_0']}
              position={[275.506, -132.947, 248.223]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.BOUT1_Mat23_0.geometry}
              material={materials['Mat.23_0']}
              position={[380.363, -180.737, 267.829]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.tB_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[380.363, -180.737, 282.948]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.BOUT2_Mat23_0.geometry}
              material={materials['Mat.23_0']}
              position={[275.506, -180.737, 267.829]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.TB2_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[275.506, -180.737, 282.948]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylindre_1_Cylindre_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[482.853, -180.49, 217.07]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylindre_Cylindre_1_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[482.899, -180.49, 212.658]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Extrusion_1_Cube_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[482.802, -180.49, 209.472]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.joint_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[327.87, -180.49, 233.939]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CRT_CAISSON_1_Mat12_0.geometry}
              material={materials['Mat.12']}
              position={[-183.252, 324.722, -162.941]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.plk_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[-183.252, 382.878, -1.862]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.joint2_Mat14_0.geometry}
              material={materials['Mat.14']}
              position={[378.721, 702.25, 254.814]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.power_2_Mat23_0.geometry}
              material={materials['Mat.23']}
              position={[378.607, 780.397, 243.078]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.bout3_Mat23_0.geometry}
              material={materials['Mat.23']}
              position={[378.721, 702.25, 249.256]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.plk2_Mat22_0.geometry}
              material={materials['Mat.22']}
              position={[378.721, 702.25, 276.845]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plan_1_Mat19_0.geometry}
              material={materials['Mat.19']}
              position={[369.636, 455.134, 283.376]}
              rotation={[-Math.PI, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Capsule_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[-624.482, 613.318, -718.902]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cache_crt_Mat14_0.geometry}
              material={materials['Mat.14']}
              position={[-183.252, 430.586, 179.863]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.dessus_Mat14_0.geometry}
              material={materials['Mat.14_1']}
              position={[-183.252, 887.55, -18.078]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.dessus_1_Mat27_0.geometry}
              material={materials['Mat.27']}
              position={[-183.252, 914.7, -18.078]}
            />
          </group>
          <group position={[126.355, -76.673, -497.614]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.inp1_Mat14_0.geometry}
              material={materials['Mat.14_2']}
              position={[546.287, 41.004, -366.471]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.stick_Mat11_0.geometry}
              material={materials['Mat.11']}
              position={[-870.656, -86.364, 144.498]}
              rotation={[0.081, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.stick2_Mat11_0.geometry}
              material={materials['Mat.11']}
              position={[656.621, -86.364, 144.498]}
              rotation={[0.081, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pied_clavier_Mat13_0.geometry}
              material={materials['Mat.13_0']}
              position={[-106.697, -117.003, 81.433]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cale_Mat12_0.geometry}
              material={materials['Mat.12']}
              position={[-105.82, -105.443, 77.077]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.clavier_cache_Mat12_0.geometry}
              material={materials['Mat.12']}
              position={[-100.115, 53.29, 89.578]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.vis_clav1_Mat2_0.geometry}
              material={materials['Mat.2_1']}
              position={[-62.329, -81.783, 123.763]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylindre_4_Extrusion_3_Mat16_0.geometry}
              material={materials['Mat.16']}
              position={[-235.824, -59.291, 146.341]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.warn_Mat10_0.geometry}
              material={materials['Mat.10']}
              position={[-105.82, -77.991, 44.759]}
              rotation={[-3.061, 0, -Math.PI]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Bool��en_Extrusion_2_Mat14_0'].geometry}
              material={materials['Mat.14_3']}
              position={[-99.576, 113.647, 158.615]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Bool��en_Extrusion_Mat4_0'].geometry}
              material={materials['Mat.4']}
              position={[-99.238, 109.278, 157.153]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.joint5_Mat14_0.geometry}
              material={materials['Mat.14_3']}
              position={[299.594, 110.31, 288.589]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Capsule_Mat15_0.geometry}
              material={materials['Mat.15']}
              position={[299.633, 104.249, 287.342]}
              rotation={[0.203, 0, 0]}
              scale={[1, 0.666, 1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.touches_Mat5_0.geometry}
              material={materials['Mat.5']}
              position={[-102.531, 130.188, 142.271]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.espace_Mat5_0.geometry}
              material={materials['Mat.5_0']}
              position={[-293.821, 81.363, 321.678]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylindre_Tube_2_Mat1_0.geometry}
              material={materials['Mat.1_0']}
              position={[524.95, 40.011, -294.64]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylindre_Tube_Mat3_0.geometry}
              material={materials['Mat.3']}
              position={[546.008, 39.385, -292.101]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Texte_3_Mat2_0.geometry}
              material={materials['Mat.2_1']}
              position={[528.118, 37.416, -298.664]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Extrusion_Cloneur_Cube_1_Mat12_0.geometry}
              material={materials['Mat.12']}
              position={[-714.855, 71.935, -258.464]}
              rotation={[0.08, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lg1_Mat14_0.geometry}
              material={materials['Mat.14_3']}
              position={[-105.672, 183.504, -94.638]}
              rotation={[0.211, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.lg2_Mat8_0.geometry}
              material={materials['Mat.8']}
              position={[-105.672, 197.625, -91.607]}
              rotation={[0.211, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.inp2_Mat14_0.geometry}
              material={materials['Mat.14_2']}
              position={[433.104, 41.004, -364.779]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CABLE_ALIM1_Mat2_0.geometry}
            material={materials['Mat.2']}
            position={[1152.246, -193.524, -1953.707]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CABLE_ALIM_2_Mat2_0.geometry}
            material={materials['Mat.2']}
            position={[1154.343, -193.522, -1941.991]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PRISE_Mat2_0.geometry}
            material={materials['Mat.2_0']}
            position={[1497.324, -182.164, -1935.269]}
            rotation={[3.111, 0, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PATTE1_Mat29_0.geometry}
            material={materials['Mat.29']}
            position={[1467.866, -178.801, -1826.051]}
            rotation={[3.111, 0, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PATTE2_Mat29_0.geometry}
            material={materials['Mat.29']}
            position={[1527.767, -178.801, -1826.051]}
            rotation={[3.111, 0, Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CABLE_ALIM_3_Mat28_0.geometry}
            material={materials['Mat.28']}
            position={[908.939, -128.545, -1199.405]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.CABLE_ALIM4_Mat28_0.geometry}
            material={materials['Mat.28']}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/computer.glb');

export default DemoComputer;